version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:11434/api/tags"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - ollama_data:/root/.ollama

  bot:
    build: .
    container_name: glpi-qwen-bot
    depends_on:
      ollama:
        condition: service_healthy
    env_file:
      - .env
    environment:
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL-http://ollama:11434}
      MODEL_NAME: ${MODEL_NAME-qwen2.5:1.5b-instruct}
      STATE_FILE: /data/state.json
      SIMILAR_INDEX_CACHE: /data/similar_index.json
    volumes:
      - bot_data:/data
    restart: unless-stopped

volumes:
  ollama_data: {}
  bot_data: {}
