name: CI

on:
  push:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests (mocked)
        env:
          SIMILAR_MAX_PAGES: "1"
          SIMILAR_PAGE_SIZE: "1"
          SIMILAR_INDEX_CACHE: ""
        run: |
          pytest -q
