name: E2E (live)

on:
  workflow_dispatch: {}

jobs:
  e2e-live:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    services:
      ollama:
        image: ollama/ollama:latest
        ports:
          - 11434:11434
        options: >-
          --health-cmd="bash -lc 'ollama serve & sleep 2 && curl -sf http://localhost:11434/api/tags || exit 1'"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=20

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for ollama & pull model
        run: |
          for i in {1..60}; do
            curl -sSf http://localhost:11434/api/tags && break || sleep 2
          done
          curl -sS -X POST http://localhost:11434/api/pull -d '{"name":"qwen2.5:1.5b-instruct"}'
          curl -sSf http://localhost:11434/api/tags | grep -i qwen

      - name: Run E2E (one shot)
        env:
          GLPI_URL: ${{ secrets.GLPI_URL }}
          GLPI_APP_TOKEN: ${{ secrets.GLPI_APP_TOKEN }}
          GLPI_USER_TOKEN: ${{ secrets.GLPI_USER_TOKEN }}
          GLPI_USER_TOKEN_TECH: ${{ secrets.GLPI_USER_TOKEN_TECH }}
          GLPI_USER_TOKEN_USER: ${{ secrets.GLPI_USER_TOKEN_USER }}
          OLLAMA_BASE_URL: "http://localhost:11434"
          MODEL_NAME: "qwen2.5:1.5b-instruct"
          DEBUG: "1"
          POLL_SECONDS: "2"
          ADAPTIVE_POLL: "0"
          MAX_TICKETS_PER_CYCLE: "5"
          MAX_HISTORY: "6"
          SIMILAR_INDEX_CACHE: ""
        run: |
          python app.py --once
